return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 14,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 14,
  nextobjectid = 270,
  properties = {},
  tilesets = {
    {
      name = "basic",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 12,
      image = "../assets/tilesets/tileset.png",
      imagewidth = 192,
      imageheight = 96,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 72,
      tiles = {}
    },
    {
      name = "orbs",
      firstgid = 73,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "../assets/tilesets/orbs.png",
      imagewidth = 16,
      imageheight = 16,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 1,
      tiles = {}
    },
    {
      name = "miscellaneus",
      firstgid = 74,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "../assets/tilesets/miscellaneus.png",
      imagewidth = 64,
      imageheight = 32,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 8,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 14,
      id = 1,
      name = "foreground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 6, 14,
        26, 26, 26, 6, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 14,
        0, 0, 0, 18, 14, 14, 14, 14, 14, 14, 26, 26, 26, 26, 27, 0, 0, 0, 1, 2, 2, 2, 2, 2, 3, 0, 0, 1, 30, 14,
        29, 3, 0, 25, 26, 26, 26, 26, 26, 27, 0, 0, 0, 0, 0, 0, 0, 1, 14, 14, 14, 14, 14, 14, 15, 0, 0, 13, 14, 14,
        14, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 14, 14, 14, 14, 14, 14, 14, 15, 0, 0, 13, 14, 14,
        14, 28, 29, 3, 0, 1, 3, 0, 1, 2, 2, 2, 2, 2, 2, 2, 14, 14, 14, 14, 26, 26, 26, 26, 27, 0, 0, 13, 14, 14,
        14, 14, 14, 28, 29, 30, 14, 29, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 27, 0, 0, 0, 0, 0, 0, 0, 13, 14, 14,
        14, 14, 5, 5, 5, 5, 5, 5, 5, 5, 26, 26, 26, 26, 26, 26, 26, 26, 27, 0, 0, 0, 0, 0, 0, 0, 0, 13, 14, 14,
        14, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 44, 44, 44, 30, 14, 14,
        26, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 14, 14, 14, 14, 14, 14,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 14, 14, 14, 14, 14, 14,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 44, 2, 14, 14, 14, 14, 14, 14, 14,
        43, 45, 0, 0, 0, 43, 44, 45, 0, 0, 0, 0, 0, 43, 44, 45, 0, 0, 0, 0, 0, 18, 14, 14, 14, 14, 14, 14, 14, 14,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 14, 14, 14, 14, 14, 14, 14, 14
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 14,
      id = 11,
      name = "miscellaneus",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 76, 0, 0, 78, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 75, 0, 0, 0, 0, 75, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 74, 75, 76, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 75, 75, 75, 0, 0, 0, 0, 0, 75, 75, 75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 14,
      id = 10,
      name = "orbs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 16,
          width = 16,
          height = 48,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = 31,
          y = 49,
          width = 1,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = 63,
          y = 81,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 80,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 111,
          y = 81,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 80,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 399,
          y = 33,
          width = 1,
          height = 62,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 432,
          y = 33,
          width = 1,
          height = 94,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 17,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 65,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 49,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 33,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 239,
          y = 33,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 255,
          y = 17,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 129,
          width = 1,
          height = 47,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 177,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 253,
          name = "",
          type = "",
          shape = "rectangle",
          x = 255,
          y = 193,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 254,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208.001,
          y = 193,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "",
          type = "",
          shape = "rectangle",
          x = 127,
          y = 193,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 193,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "",
          shape = "rectangle",
          x = 31,
          y = 193,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "",
          shape = "rectangle",
          x = 31,
          y = 129,
          width = 1,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "",
          shape = "rectangle",
          x = 303,
          y = 113,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "",
          shape = "rectangle",
          x = 319,
          y = 97,
          width = 1,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "solid",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 64,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 48,
          width = 95,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 48,
          width = 31,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 80,
          width = 47,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 96,
          width = 48,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          type = "",
          shape = "rectangle",
          x = 81,
          y = 80,
          width = 30,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "",
          shape = "rectangle",
          x = 129,
          y = 80,
          width = 270,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 32,
          width = 79,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 16,
          width = 15,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 0,
          width = 208,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 289,
          y = 32,
          width = 110,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 273,
          y = 48,
          width = 126,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 257,
          y = 64,
          width = 142,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 433,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 369,
          y = 128,
          width = 110,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "rectangle",
          x = 321,
          y = 176,
          width = 48,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "",
          shape = "rectangle",
          x = 209,
          y = 192,
          width = 46,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          type = "",
          shape = "rectangle",
          x = 81,
          y = 192,
          width = 46,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 112,
          width = 271,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 31,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 31,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 96,
          width = 15,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "torch",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 268,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 168,
          width = 8,
          height = 24,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "player",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "door",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 168,
          width = 24,
          height = 24,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "mushrooms",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 264,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 114,
          width = 14,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 178,
          width = 14,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 178,
          width = 14,
          height = 14,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "spikes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 208,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 209,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 210,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 213,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 214,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 215,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 216,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 217,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 218,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 220,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 226,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flipped_v"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "stones",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 205,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "hint",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 269,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["hint_text"] = "SHIFT SPRINT"
          }
        }
      }
    }
  }
}
